In [2]:
import numpy as np
import scipy.linalg

def nullspace(A, atol=1e-13, rtol=0):
    A = np.atleast_2d(A)
    u, s, vh = np.linalg.svd(A)
    tol = max(atol, rtol * s[0])
#     nnz = (s >= tol).sum()
#     nnz = s.sum()
    nnz = (s > 0).sum()
#     ns = vh[nnz:].conj().T
    ns = vh[nnz:].T
    return ns

In [3]:
from operator import add
from itertools import chain, combinations
from functools import reduce

import numpy as np
from scipy import ndimage

In [14]:
H = np.mat( [[1,1,1,1,0,0],
             [0,0,1,1,0,1],
             [1,0,0,1,1,0]] )

G = np.mat( [[1,0,0,1,0,1],
             [0,1,0,1,1,1],
             [0,0,1,1,1,0]] )

In [15]:
GT2 = nullspace(H)
G2 = GT2.T

In [16]:
G2

matrix([[-0.58663655,  0.3077577 , -0.33168172,  0.61056057, -0.02392402,
         -0.27887885],
        [-0.38943943,  0.27392402,  0.4232731 , -0.3077577 ,  0.69719713,
         -0.1155154 ],
        [ 0.06476489,  0.57467454, -0.45915914, -0.18028029,  0.1155154 ,
          0.63943943]])

In [4]:
def gjel(A):
    """Gauss-Jordan elimination."""
    nulldim = 0
    for i, row1 in enumerate(A):
        pivot = A[i:, i].argmax() + i
        if A[pivot, i] == 0:
            nulldim = len(A) - i
            break
        new_row = A[pivot] / A[pivot, i]
        A[pivot] = A[i]
        row1[:] = new_row
        
        for j, row2 in enumerate(A):
            if j == i:
                continue
            row2[:] -= new_row*A[j, i]
    return A, nulldim

In [6]:
G = np.mat( [[1,1,1,1,0,0],
             [0,0,1,1,0,1],
             [1,0,0,1,1,0]] )

In [43]:
H = np.mat( [[1,1,1,1,0,0],
             [0,0,1,1,0,1],
             [1,0,0,1,1,0]] )

G = np.mat( [[1,0,0,1,0,1],
             [0,1,0,1,1,1],
             [0,0,1,1,1,0]] )

In [21]:
H.shape

(3, 6)

In [9]:
gjel(G)[0]

matrix([[1, 0, 0, 1, 0, 1],
        [0, 1, 0, 1, 1, 1],
        [0, 0, 1, 1, 1, 0]])

In [11]:
gjel(H)[0]

matrix([[1, 0, 0, 1, 1, 0],
        [0, 1, 0, 1, 1, 1],
        [0, 0, 1, 1, 0, 1]])

In [176]:
import sympy

H = np.mat([ [0,0,0,1,1,1,1],
           [0,1,1,0,0,1,1],
           [1,0,1,0,1,0,1]])

In [188]:
H = [[2,1,2,1,2,0,1,0,0,0,0],
[1,1,0,1,1,1,0,1,0,0,0],
[1,1,1,0,2,2,0,0,1,0,0],
[1,2,2,1,0,2,0,0,0,1,0],
[0,1,2,2,1,2,0,0,0,0,1]]

In [191]:
sympy.Matrix(H).T.rref()[1]

(0, 1, 2, 3, 4)

In [185]:
np.linalg.eig(np.array(H).T)

LinAlgError: Last 2 dimensions of the array must be square

In [252]:
matrix = G
q = 2
H = transforms(matrix=matrix, field=q)
len(sympy.Matrix(H).T.rref()[1])

3

In [248]:
G.shape

(4, 7)

In [246]:
G.shape

(4, 7)

In [255]:
print('distance: ' + str(len(sympy.Matrix(H).T.rref()[1])))

distance: 3


In [288]:
for strng in range(H.shape[0]):
    print(''.join([str(i) for i in np.array(H[strng]).flatten()]))

0111100
1011010
1101001


In [264]:
''.join(str(e) for e in H[strng])

'[[1 1 0 1 0 0 1]]'

In [286]:
''.join([str(i) for i in np.array(H[strng]).flatten()])

'1101001'

In [283]:
np.array(H[strng])

array([[1, 1, 0, 1, 0, 0, 1]])

In [314]:
H = np.mat([ [0,0,0,1,1,1,1],
           [0,1,1,0,0,1,1],
           [1,0,1,0,1,0,1]])

### дана матрица G найти H
G = np.mat([[1,1,1,0,0,0,0],
           [1,0,0,1,1,0,0],
           [0,1,0,1,0,1,0],
           [1,1,0,1,0,0,1]])

In [316]:
G = transforms(matrix=H, field=q)
G

matrix([[0, 0, 1, 1, 0, 0, 0],
        [1, 0, 1, 0, 1, 0, 0],
        [0, 1, 1, 0, 0, 1, 0],
        [1, 1, 1, 0, 0, 0, 1]])

In [307]:
matrix = H

H = matrix
G = transforms(matrix=matrix, field=q)
d = len(sympy.Matrix(H).T.rref()[1])
print('distance: ' + str(d))
print('generator matrix:')
for strng in range(G.shape[0]):
    print(''.join([str(i) for i in np.array(G[strng]).flatten()]))

distance: 3
generator matrix:
0011000
1010100
0110010
1110001


In [304]:

H = matrix
G = transforms(matrix=matrix, field=q)
d = len(sympy.Matrix(H).T.rref()[1])
print('distance: ' + str(d))
print('generator matrix:')
for strng in range(G.shape[0]):
    print(''.join([str(i) for i in np.array(G[strng]).flatten()]))

distance: 3
generator matrix:
0011000
1010100
0110010
1110001


In [305]:
first = ['0011000',
'1010100',
'0110010',
'1110001']

for i in first:
    print(i)

0011000
1010100
0110010
1110001


In [310]:
type_mat = 'parity 1'

In [313]:
q = int(q)

if type_mat.split(' ')[0] == 'parity':
    H = matrix
    G = transforms(matrix=matrix, field=q)
    d = len(sympy.Matrix(H).T.rref()[1])
    print('distance: ' + str(d))
    print('generator matrix:')
    for strng in range(G.shape[0]):
        print(''.join([str(i) for i in np.array(G[strng]).flatten()]))
    
    
    
if type_mat.split(' ')[0] == 'generator':
    G = matrix
    H = transforms(matrix=matrix, field=q)
    d = len(sympy.Matrix(H).T.rref()[1])
    print('distance: ' + str(d))
    print('parity check matrix:')    
    for strng in range(H.shape[0]):
        print(''.join([str(i) for i in np.array(H[strng]).flatten()]))



distance: 3
generator matrix:
0011000
1010100
0110010
1110001


In [306]:
def gjel(A, p):
    """Gauss-Jordan elimination."""
    nulldim = 0
    for i, row1 in enumerate(A):
        pivot = A[i:, i].argmax() + i
        if A[pivot, i] == 0:
            nulldim = (len(A) - i) % p #####
            break
        new_row = (A[pivot] * A[pivot, i]) % p #####
        A[pivot] = A[i]
        row1[:] = new_row
        
        for j, row2 in enumerate(A):
            if j == i:
                continue
            row2[:] = (row2[:] - new_row*A[j, i]) % p ####
    return A, nulldim

def transforms(matrix, field):
    k, n = matrix.shape
    matrix = gjel(matrix, p=field)[0]
    new_matrix = np.hstack((-matrix[:,k:].T, np.diag([1]*(n-k))) ) % field
    
    return new_matrix

In [239]:
transforms(G, field=2).shape

(3, 7)

In [238]:
0001111
0110011
1010101

matrix([[1, 0, 0, 0, 0, 1, 1],
        [0, 1, 0, 0, 1, 0, 1],
        [0, 0, 1, 0, 1, 1, 0],
        [0, 0, 0, 1, 1, 1, 1]])

In [240]:
H = np.mat([ [0,0,0,1,1,1,1],
           [0,1,1,0,0,1,1],
           [1,0,1,0,1,0,1]])

In [291]:
transforms(H, field=2)

matrix([[1, 1, 1, 1, 0, 0, 0],
        [0, 1, 1, 0, 1, 0, 0],
        [1, 0, 1, 0, 0, 1, 0],
        [0, 0, 1, 0, 0, 0, 1]])

In [249]:
H = np.mat([ [0,0,0,1,1,1,1],
           [0,1,1,0,0,1,1],
           [1,0,1,0,1,0,1]])

### дана матрица G найти H
G = np.mat([[1,1,1,0,0,0,0],
           [1,0,0,1,1,0,0],
           [0,1,0,1,0,1,0],
           [1,1,0,1,0,0,1]])

k, n = G.shape

# приводим G к стандартному виду
G = gjel(G)[0]

# отрезаем k столбцов и стакаем с единичной матрицей, получаем искомую матрицу H
H_new = np.hstack((-G[:,k:].T, np.diag([1]*(n-k))) ) % 2
print(H_new)
print('--------')
print()

## заглядываем в условие и находим там H, кторую должны были получить,
## приводим ее к стандартному ввиду и приводим к стандартному ввиду полученую матрицу

print(gjel(H)[0])
print('----------')
print(gjel(H_new)[0])

TypeError: gjel() missing 1 required positional argument: 'p'

In [ ]:
q: 2
parity check matrix:
0001111
0110011
1010101

In [215]:
q = 'q: 2'

In [219]:
q.split(' ')[0]

'q:'

In [195]:
import sys

In [226]:
###INPUT

c = 0
for number, line in enumerate(sys.stdin):
    if number == 0:
        q = line.split(' ')[1]
    if number == 1:
        type_mat = line
    if number > 1:
        if c == 0:
            line = line.split('\n')[0]
            matrix = list(map(int, line))
            matrix = np.mat(matrix)
            c += 1
        else:
            line = line.split('\n')[0]
            line_mat = list(map(int, line))
            matrix = np.vstack((matrix, line_mat))

q: 2


NameError: name 'type_mat' is not defined

In [223]:
l = [2, 1, 2, 1, 2, 0, 1, 0, 0, 0, 0]

In [224]:
np.mat(l)

matrix([[2, 1, 2, 1, 2, 0, 1, 0, 0, 0, 0]])

In [220]:
for n, i in enumerate(range(9, 100)):
    print(n)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90


In [231]:
line = '21212010000\n'.split('\n')[0]
line

'21212010000'

In [214]:
np.vstack((np.mat(list(map(int, '21212010000'))), list(map(int, line))))

matrix([[2, 1, 2, 1, 2, 0, 1, 0, 0, 0, 0],
        [2, 1, 2, 1, 2, 0, 1, 0, 0, 0, 0]])

In [ ]:
q = input()

In [193]:
while True:
    try:
        try:
            line = input()
        except (ValueError, EOFError):
            break
        # здесь можно как-то строку обработать
        print(line)

SyntaxError: unexpected EOF while parsing (<ipython-input-193-0283da9b88b4>, line 8)

In [166]:
G

matrix([[1, 0, 0, 0, 0, 1, 1],
        [0, 1, 0, 0, 1, 0, 1],
        [0, 0, 1, 0, 1, 1, 0],
        [0, 0, 0, 1, 1, 1, 1]])

In [118]:
def n_k(matrix):
    k,n = matrix.shape
    return k,n

In [122]:
n, k = n_k(G)

In [157]:
k, n = n_k(G)

In [125]:
n-k

-3

In [156]:
-gjel(G)[0][]

matrix([[-1,  0,  0,  0,  0, -1, -1],
        [ 0, -1,  0,  0, -1,  0, -1],
        [ 0,  0, -1,  0, -1, -1,  0],
        [ 0,  0,  0, -1, -1, -1, -1]])

In [161]:
gjel(np.hstack((-gjel(G)[0][:,k:].T, np.diag([1]*(n-k)))) % 2)[0]

matrix([[1, 0, 1, 1, 0, 1, 0],
        [0, 1, 1, 1, 1, 0, 0],
        [0, 0, 0, 1, 1, 1, 1]])

In [160]:
gjel(H)[0]

matrix([[1, 0, 1, 0, 1, 0, 1],
        [0, 1, 1, 0, 0, 1, 1],
        [0, 0, 0, 1, 1, 1, 1]])

In [152]:
gjel(np.hstack((gjel(G)[0][:,3:].T, np.eye(4,3))))[0]

matrix([[1., 0., 1., 1., 0., 0., 1.],
        [0., 1., 1., 1., 0., 1., 0.],
        [0., 0., 0., 1., 1., 0., 0.],
        [0., 0., 0., 1., 0., 1., 1.]])

In [151]:
gjel(H)[0]

matrix([[1, 0, 1, 0, 1, 0, 1],
        [0, 1, 1, 0, 0, 1, 1],
        [0, 0, 0, 1, 1, 1, 1]])

In [37]:
(- gjel(G)[0][:,3:].T) % 2

matrix([[0, 0, 0, 1],
        [0, 1, 1, 1],
        [1, 0, 1, 1],
        [1, 1, 0, 1]])

In [58]:
gjel(np.hstack((((- gjel(H)[0][:,3:].T) % 2), np.eye(3,3))))

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [77]:
gjel(G)[0].shape

(4, 7)

In [81]:
gjel(np.hstack((((- gjel(H)[0][:,3:].T) % 2), np.eye(4,4))))[0]

matrix([[1., 0., 0., 0., 0., 1., 1.],
        [0., 1., 0., 0., 1., 0., 1.],
        [0., 0., 1., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1., 1.]])

4

In [79]:
gjel(np.hstack((((- gjel(G)[0][:,3:].T) % 2), np.eye(3,3))))[0]

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [109]:
gjel(np.hstack((((- gjel(H)[0][:,-4:].T) % 2), np.eye(4,4))))[0]

matrix([[1., 0., 0., 0., 0., 1., 1.],
        [0., 1., 0., 0., 1., 0., 1.],
        [0., 0., 1., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1., 1.]])

In [108]:
gjel(H)[0]

matrix([[1, 0, 1, 0, 1, 0, 1],
        [0, 1, 1, 0, 0, 1, 1],
        [0, 0, 0, 1, 1, 1, 1]])

In [90]:
gjel(G)[0]

matrix([[1, 0, 0, 0, 0, 1, 1],
        [0, 1, 0, 0, 1, 0, 1],
        [0, 0, 1, 0, 1, 1, 0],
        [0, 0, 0, 1, 1, 1, 1]])

In [78]:
7-4

3

In [19]:
H.shape

(3, 6)

In [12]:
def gjel(A):
    """Gauss-Jordan elimination."""
    nulldim = 0
    for i, row1 in enumerate(A):
        pivot = A[i:, i].argmax() + i
        if A[pivot, i] == 0:
            nulldim = (len(A) - i) % 2 #####
            break
        new_row = (A[pivot] * A[pivot, i]) % 2 #####
        A[pivot] = A[i]
        row1[:] = new_row
        
        for j, row2 in enumerate(A):
            if j == i:
                continue
            row2[:] = (row2[:] - new_row*A[j, i]) % 2 ####
    return A, nulldim

In [35]:
(- gjel(H)[0][:,3:].T) % 2

matrix([[1, 1, 1],
        [1, 1, 0],
        [0, 1, 1]])

In [40]:
np.hstack((((- gjel(H)[0][:,3:].T) % 2), np.eye(3,3)))

matrix([[1., 1., 1., 1., 0., 0.],
        [1., 1., 0., 0., 1., 0.],
        [0., 1., 1., 0., 0., 1.]])

In [32]:
gjel(H)[0][:,3:]

matrix([[1, 1, 0],
        [1, 1, 1],
        [1, 0, 1]])