In [13]:
import numpy as np
import scipy.linalg

def nullspace(A, atol=1e-13, rtol=0):
    A = np.atleast_2d(A)
    u, s, vh = np.linalg.svd(A)
    tol = max(atol, rtol * s[0])
#     nnz = (s >= tol).sum()
#     nnz = s.sum()
    nnz = (s > 0).sum()
#     ns = vh[nnz:].conj().T
    ns = vh[nnz:].T
    return ns

In [18]:
from operator import add
from itertools import chain, combinations
from functools import reduce

import numpy as np
from scipy import ndimage

In [14]:
H = np.mat( [[1,1,1,1,0,0],
             [0,0,1,1,0,1],
             [1,0,0,1,1,0]] )

G = np.mat( [[1,0,0,1,0,1],
             [0,1,0,1,1,1],
             [0,0,1,1,1,0]] )

In [15]:
GT2 = nullspace(H)
G2 = GT2.T

In [16]:
G2

matrix([[-0.58663655,  0.3077577 , -0.33168172,  0.61056057, -0.02392402,
         -0.27887885],
        [-0.38943943,  0.27392402,  0.4232731 , -0.3077577 ,  0.69719713,
         -0.1155154 ],
        [ 0.06476489,  0.57467454, -0.45915914, -0.18028029,  0.1155154 ,
          0.63943943]])

In [ ]:
def gjel(A):
    """Gauss-Jordan elimination."""
    nulldim = 0
    for i, row1 in enumerate(A):
        pivot = A[i:, i].argmax() + i
        if A[pivot, i] == 0:
            nulldim = len(A) - i
            break
        new_row = A[pivot] / A[pivot, i]
        A[pivot] = A[i]
        row1[:] = new_row
        
        for j, row2 in enumerate(A):
            if j == i:
                continue
            row2[:] -= new_row*A[j, i]
    return A, nulldim

In [19]:
G = np.mat( [[1,1,1,1,0,0],
             [0,0,1,1,0,1],
             [1,0,0,1,1,0]] )

In [21]:
def gjel(A):
    """Gauss-Jordan elimination."""
    nulldim = 0
    for i, row1 in enumerate(A):
        pivot = A[i:, i].argmax() + i
        if A[pivot, i] == 0:
            nulldim = (len(A) - i) % 2 #####
            break
        new_row = (A[pivot] * A[pivot, i]) % 2 #####
        A[pivot] = A[i]
        row1[:] = new_row
        
        for j, row2 in enumerate(A):
            if j == i:
                continue
            row2[:] = (row2[:] - new_row*A[j, i]) % 2 ####
    return A, nulldim

In [35]:
(- gjel(H)[0][:,3:].T) % 2

matrix([[1, 1, 1],
        [1, 1, 0],
        [0, 1, 1]])

In [40]:
np.hstack((((- gjel(H)[0][:,3:].T) % 2), np.eye(3,3)))

matrix([[1., 1., 1., 1., 0., 0.],
        [1., 1., 0., 0., 1., 0.],
        [0., 1., 1., 0., 0., 1.]])

In [32]:
gjel(H)[0][:,3:]

matrix([[1, 1, 0],
        [1, 1, 1],
        [1, 0, 1]])